FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y cron --no-cache=true
RUN apt-get install -y vim
RUN apt-get -y install git

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip \
  && pip3 install yfinance --upgrade --no-cache-dir \
  && pip3 install pandas

COPY mainService.sh /var/mainService.sh
COPY mainCron.sh /var/mainCron.sh

ENTRYPOINT cd /var && sh mainService.sh
